---
- hosts: localhost
  connection: local
  become: yes

  pre_tasks:
    - name: Update the OS Repo
      yum:
        update_cache=yes
        state=latest
  tasks:
    - import: tasks/pakages.yml
...

